### ISSUE TITLE
How to Retrieve an Archive if the ArchiveID begins with a hyphen, minus or dash

### ISSUE THREAD

**Issue by jeffreykoch** [gburca/amazon-glacier-cmd-interface#4]
Attempted to retrieve an archive where the ArchiveID begins with a minus sign. The interface views that as a command line option and generates an error message - glacier-cmd getarchive: error: too few arguments

Example: ArchiveID = -Fga5p0_Vgu8CRoA1jc24SSCa7Z6njwYVwns................................

Tried escaping the ID, surounding the ID with single and double quotes. No success

Any ideas?

Jeff

**Comment by gburca** [comment]
As mentioned in the instructions, preceede the archive ID with --. That indicates the end of the options.

**Comment by jeffreykoch** [comment]
Thanks
